name: SOTGrps
version: "1.2"
license: "GPL-2.0-or-later"
date: 2023-06-20
description: |
    Constructing and identifying groups of small order type

authors:
    - name: Eileen Pan
      url: https://xpan-eileen.github.io/about/

maintainers:
    - name: Eileen Pan
      url: https://xpan-eileen.github.io/about/
    - name: Max Horn
      url: https://www.quendi.de/math

GAP: ">=4.10"

www: https://gap-packages.github.io/sotgrps/
readme: README.md
packageinfo: https://gap-packages.github.io/sotgrps//PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/sotgrps/releases/download/v1.2/SOTGrps-1.2.tar.gz

abstract: |
    The <span class="pkgname">SOTGrps</span> package contains methods to construct up to isomorphism the groups of a small order type.

status: other
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    construction of finite groups, identification of finite groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>PH23</span>]   <b class='BibAuthor'>Pan, E. and Horn, M.</b>,
     <i class='BibTitle'>SOTGrps, Constructing and identifying groups of small order type,
             Version 1.2</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/sotgrps/">https://gap-packages.github.io/sotgrps/</a></span>.
    </p>
    

bibtex: |
    @misc{ SOTGrps1.2,
      author =           {Pan, E. and Horn, M.},
      title =            {{SOTGrps},  Constructing  and  identifying  groups  of
                          small order type, {V}ersion 1.2},
      month =            {Jun},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/sotgrps/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{sotgrps/}}},
      keywords =         {construction   of  finite  groups;  identification  of
                          finite groups},
      printedkey =       {PH23}
    }

